=== MSLNZ/GTC/GTC/gtc_v_1_4_2.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "JSON Schema for GTC archive v1.4.2",
  "$defs": {
    "eUIDString": {
      "type": "string",
      "pattern": "^\\(\\d+,\\s*\\d+\\)$"
    },
    "iUIDString": {
      "type": "string",
      "pattern": "^\\(\\d+,\\s*\\d+,\\s*0\\)$"
    },
    "string_or_null" : { 
      "anyOf": [
        { "type": "string" },
        { "enum": [ null ] }
      ]
    },
    "df": {
      "anyOf": [
        { "type": "number","minimum": 0 },
        { "enum": [ null ] }
      ]
    },
    "correlation": {
      "type": "object",
      "propertyNames": {"$ref": "#/$defs/eUIDString"},
      "minProperties": 2,
      "maxProperties": 2
    },
    "ensemble": {
      "type": "array",
      "items": { "$ref": "#/$defs/eUIDString" },
      "minItems": 0
    },
    "eUID_array": {
      "type": "array",
      "items": { "$ref": "#/$defs/eUIDString" },
      "minItems": 0
    },
    "eVector": {
      "type": "object",
      "properties": {
         "CLASS": { "const": "Vector" },
         "index": { "$ref": "#/$defs/eUID_array" },
         "value": { 
           "type": "array", 
           "items": { "type": "number" }, 
           "minItems": 0 
        }
      },
      "required": ["CLASS","index","value"],
      "additionalProperties": false
    },
    "iUID_array": {
      "type": "array",
      "items": { "$ref": "#/$defs/iUIDString" },
      "minItems": 0
    },
    "iVector": {
      "type": "object",
      "properties": {
         "CLASS": { "const": "Vector" },
         "index": { "$ref": "#/$defs/iUID_array" },
         "value": { 
           "type": "array", 
           "items": { "type": "number" }, 
           "minItems": 0 
        }
      },
      "required": ["CLASS","index","value"],
      "additionalProperties": false
    },
    "elementaryReal": {
      "type": "object",
      "properties": {
          "CLASS": { "const": "ElementaryReal" },
          "x": { "type": "number" },
          "uid": { "$ref": "#/$defs/eUIDString" }
      },
      "required": ["CLASS","x","uid"],
      "additionalProperties": false
    },
    "IntermediateReal": {
      "type": "object",
      "properties": {
          "CLASS": { "const": "IntermediateReal" },
          "value": { "type": "number" },
          "label": { "$ref": "#/$defs/string_or_null" },
          "uid": { "$ref": "#/$defs/iUIDString" },
          "u_components" : { "$ref": "#/$defs/eVector" },
          "d_components" : { "$ref": "#/$defs/eVector" },
          "i_components" : { "$ref": "#/$defs/iVector" }
      },
      "required": [
        "CLASS","value","label","uid", 
        "u_components", 
        "d_components", 
        "i_components"
      ],
      "additionalProperties": false
    },
    "Complex" : {
      "type": "object",
      "properties": {
          "CLASS": { "const": "Complex" },
          "n_re" : { "type": "string" },
          "n_im" : { "type": "string" },
          "label": { "$ref": "#/$defs/string_or_null" }
      },
      "required": ["CLASS","n_re","n_im","label"],
      "additionalProperties": false
    },
    "leaf_node": {
      "type": "object",
      "properties": {
        "CLASS": { "const": "LeafNode" },
        "uid": {"$ref": "#/$defs/eUIDString" },
        "label": { "$ref": "#/$defs/string_or_null" },
        "u": { "type": "number", "minValue": 0 },
        "df": { "$ref": "#/$defs/df" },
        "complex": {
          "type" : "array",
          "items": { "$ref": "#/$defs/eUIDString" },
          "minItems": 2,
          "maxItems": 2     	 
        },
        "independent": {"type": "boolean" },
        "correlation": {"$ref": "#/$defs/correlation"},
        "ensemble": {"$ref": "#/$defs/ensemble"}
      },
      "required": ["CLASS", "uid", "u" ],
      "dependencies": {
      	"ensemble": {
        	"required": ["correlation"]
        },
        "correlation": {
        	"required": ["ensemble"]
        }
      },
      "additionalProperties": false    
    },
    "tagged": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z_][a-zA-Z0-9_]*$": {
          "type": "object",
          "properties": { "CLASS": { "type": "string" } },
          "if": { "properties": { "CLASS": { "const": "ElementaryReal" } } },
          "then": {"$ref": "#/$defs/elementaryReal" },
          "else": {
            "if": { "properties": { "CLASS": { "const": "IntermediateReal" } } },
            "then": {"$ref": "#/$defs/IntermediateReal"},
            "else":{
              "if":{ "properties": { "CLASS": { "const": "Complex" } },
              "then": {"$ref": "#/$defs/Complex"} },
              "else": {
                "type": "object",  
                "additionalProperties": false,
                "errorMessage": "Unexpected value for CLASS property"
              }
            }
          }
        }
      },
      "additionalProperties": false      
    }    
  },
  "type": "object",
  "properties": {
    "CLASS": { "const": "Archive" },
    "$id": { "type": "string" },
    "leaf_nodes": {
      "type": "object",
      "patternProperties": {
        "^\\(\\d+,\\s*\\d+\\)$": { "$ref": "#/$defs/leaf_node" },
        "additionalProperties": false
      }
    },
    "tagged_complex": { "$ref": "#/$defs/tagged" },
    "tagged_real": { "$ref": "#/$defs/tagged" },
    "untagged_real": { "$ref": "#/$defs/tagged" },
    "intermediate_uids": {
      "type": "object",
      "patternProperties": {
        "^\\(\\d+,\\s*\\d+,\\s*\\d+\\)$": {  
            "type": "array",
            "items": [
                { "$ref": "#/$defs/string_or_null" },
                { "type": "number" },
                { "$ref": "#/$defs/df" }
            ]
        },
        "additionalProperties": false
      }        
    }
  },
  "required": [
    "CLASS", 
    "leaf_nodes", 
    "tagged_complex", 
    "tagged_real", 
    "untagged_real", 
    "intermediate_uids"
  ],
  "additionalProperties": false
}

=== MSLNZ/GTC/test/ref_file_v_1_4_2.json
{
  "CLASS": "Archive",
  "leaf_nodes": {
    "(280662211837031421377505349403711176578, 1)": {
      "CLASS": "LeafNode",
      "uid": "(280662211837031421377505349403711176578, 1)",
      "label": null,
      "u": 1.0,
      "df": null,
      "independent": true
    },
    "(280662211837031421377505349403711176578, 2)": {
      "CLASS": "LeafNode",
      "uid": "(280662211837031421377505349403711176578, 2)",
      "label": null,
      "u": 1.0,
      "df": null,
      "independent": true
    },
    "(280662211837031421377505349403711176578, 3)": {
      "CLASS": "LeafNode",
      "uid": "(280662211837031421377505349403711176578, 3)",
      "label": "x1",
      "u": 1.0,
      "df": 3.0,
      "independent": true
    },
    "(280662211837031421377505349403711176578, 4)": {
      "CLASS": "LeafNode",
      "uid": "(280662211837031421377505349403711176578, 4)",
      "label": "y1",
      "u": 1.0,
      "df": 4.0,
      "independent": true
    },
    "(280662211837031421377505349403711176578, 5)": {
      "CLASS": "LeafNode",
      "uid": "(280662211837031421377505349403711176578, 5)",
      "label": null,
      "u": 1.0,
      "df": null,
      "independent": false,
      "correlation": {
        "(280662211837031421377505349403711176578, 5)": 1.0,
        "(280662211837031421377505349403711176578, 6)": 0.5
      },
      "ensemble": []
    },
    "(280662211837031421377505349403711176578, 6)": {
      "CLASS": "LeafNode",
      "uid": "(280662211837031421377505349403711176578, 6)",
      "label": null,
      "u": 1.0,
      "df": null,
      "independent": false,
      "correlation": {
        "(280662211837031421377505349403711176578, 6)": 1.0,
        "(280662211837031421377505349403711176578, 5)": 0.5
      },
      "ensemble": []
    },
    "(280662211837031421377505349403711176578, 7)": {
      "CLASS": "LeafNode",
      "uid": "(280662211837031421377505349403711176578, 7)",
      "label": null,
      "u": 1.0,
      "df": 4.0,
      "independent": false,
      "correlation": {
        "(280662211837031421377505349403711176578, 7)": 1.0,
        "(280662211837031421377505349403711176578, 8)": 0.5
      },
      "ensemble": [
        "(280662211837031421377505349403711176578, 8)",
        "(280662211837031421377505349403711176578, 7)"
      ]
    },
    "(280662211837031421377505349403711176578, 8)": {
      "CLASS": "LeafNode",
      "uid": "(280662211837031421377505349403711176578, 8)",
      "label": null,
      "u": 1.0,
      "df": 4.0,
      "independent": false,
      "correlation": {
        "(280662211837031421377505349403711176578, 8)": 1.0,
        "(280662211837031421377505349403711176578, 7)": 0.5
      },
      "ensemble": [
        "(280662211837031421377505349403711176578, 8)",
        "(280662211837031421377505349403711176578, 7)"
      ]
    },
    "(280662211837031421377505349403711176578, 9)": {
      "CLASS": "LeafNode",
      "uid": "(280662211837031421377505349403711176578, 9)",
      "label": null,
      "u": 3.1622776601683795,
      "df": 5.0,
      "independent": false,
      "complex": [
        "(280662211837031421377505349403711176578, 9)",
        "(280662211837031421377505349403711176578, 10)"
      ],
      "correlation": {
        "(280662211837031421377505349403711176578, 9)": 1.0,
        "(280662211837031421377505349403711176578, 10)": 0.19999999999999996
      },
      "ensemble": []
    },
    "(280662211837031421377505349403711176578, 10)": {
      "CLASS": "LeafNode",
      "uid": "(280662211837031421377505349403711176578, 10)",
      "label": null,
      "u": 3.1622776601683795,
      "df": 5.0,
      "independent": false,
      "complex": [
        "(280662211837031421377505349403711176578, 9)",
        "(280662211837031421377505349403711176578, 10)"
      ],
      "correlation": {
        "(280662211837031421377505349403711176578, 10)": 1.0,
        "(280662211837031421377505349403711176578, 9)": 0.19999999999999996
      },
      "ensemble": []
    },
    "(280662211837031421377505349403711176578, 11)": {
      "CLASS": "LeafNode",
      "uid": "(280662211837031421377505349403711176578, 11)",
      "label": null,
      "u": 3.1622776601683795,
      "df": 7.0,
      "independent": false,
      "complex": [
        "(280662211837031421377505349403711176578, 11)",
        "(280662211837031421377505349403711176578, 12)"
      ],
      "correlation": {
        "(280662211837031421377505349403711176578, 11)": 1.0,
        "(280662211837031421377505349403711176578, 12)": 0.19999999999999996
      },
      "ensemble": []
    },
    "(280662211837031421377505349403711176578, 12)": {
      "CLASS": "LeafNode",
      "uid": "(280662211837031421377505349403711176578, 12)",
      "label": null,
      "u": 3.1622776601683795,
      "df": 7.0,
      "independent": false,
      "complex": [
        "(280662211837031421377505349403711176578, 11)",
        "(280662211837031421377505349403711176578, 12)"
      ],
      "correlation": {
        "(280662211837031421377505349403711176578, 12)": 1.0,
        "(280662211837031421377505349403711176578, 11)": 0.19999999999999996
      },
      "ensemble": []
    }
  },
  "tagged_real": {
    "w": {
      "CLASS": "ElementaryReal",
      "x": 1.0,
      "uid": "(280662211837031421377505349403711176578, 1)"
    },
    "x": {
      "CLASS": "ElementaryReal",
      "x": 2.0,
      "uid": "(280662211837031421377505349403711176578, 2)"
    },
    "y": {
      "CLASS": "IntermediateReal",
      "value": 3.0,
      "label": null,
      "uid": "(280662211837031421377505349403711176578, 1, 0)",
      "u_components": {
        "CLASS": "Vector",
        "index": [
          "(280662211837031421377505349403711176578, 1)",
          "(280662211837031421377505349403711176578, 2)"
        ],
        "value": [
          1.0,
          1.0
        ]
      },
      "d_components": {
        "CLASS": "Vector",
        "index": [],
        "value": []
      },
      "i_components": {
        "CLASS": "Vector",
        "index": [
          "(280662211837031421377505349403711176578, 1, 0)"
        ],
        "value": [
          1.4142135623730951
        ]
      }
    },
    "z": {
      "CLASS": "IntermediateReal",
      "value": 6.0,
      "label": null,
      "uid": "(280662211837031421377505349403711176578, 2, 0)",
      "u_components": {
        "CLASS": "Vector",
        "index": [
          "(280662211837031421377505349403711176578, 1)",
          "(280662211837031421377505349403711176578, 2)"
        ],
        "value": [
          2.0,
          5.0
        ]
      },
      "d_components": {
        "CLASS": "Vector",
        "index": [],
        "value": []
      },
      "i_components": {
        "CLASS": "Vector",
        "index": [
          "(280662211837031421377505349403711176578, 1, 0)",
          "(280662211837031421377505349403711176578, 2, 0)"
        ],
        "value": [
          2.8284271247461903,
          5.385164807134504
        ]
      }
    },
    "z1": {
      "CLASS": "IntermediateReal",
      "value": 3.0,
      "label": null,
      "uid": "(280662211837031421377505349403711176578, 3, 0)",
      "u_components": {
        "CLASS": "Vector",
        "index": [
          "(280662211837031421377505349403711176578, 3)",
          "(280662211837031421377505349403711176578, 4)"
        ],
        "value": [
          1.0,
          1.0
        ]
      },
      "d_components": {
        "CLASS": "Vector",
        "index": [],
        "value": []
      },
      "i_components": {
        "CLASS": "Vector",
        "index": [
          "(280662211837031421377505349403711176578, 3, 0)"
        ],
        "value": [
          1.4142135623730951
        ]
      }
    },
    "x2": {
      "CLASS": "ElementaryReal",
      "x": 1.0,
      "uid": "(280662211837031421377505349403711176578, 5)"
    },
    "y2": {
      "CLASS": "ElementaryReal",
      "x": 2.0,
      "uid": "(280662211837031421377505349403711176578, 6)"
    },
    "z2": {
      "CLASS": "IntermediateReal",
      "value": 3.0,
      "label": null,
      "uid": "(280662211837031421377505349403711176578, 4, 0)",
      "u_components": {
        "CLASS": "Vector",
        "index": [],
        "value": []
      },
      "d_components": {
        "CLASS": "Vector",
        "index": [
          "(280662211837031421377505349403711176578, 5)",
          "(280662211837031421377505349403711176578, 6)"
        ],
        "value": [
          1.0,
          1.0
        ]
      },
      "i_components": {
        "CLASS": "Vector",
        "index": [
          "(280662211837031421377505349403711176578, 4, 0)"
        ],
        "value": [
          1.7320508075688772
        ]
      }
    },
    "x3": {
      "CLASS": "ElementaryReal",
      "x": 1.0,
      "uid": "(280662211837031421377505349403711176578, 7)"
    },
    "y3": {
      "CLASS": "ElementaryReal",
      "x": 2.0,
      "uid": "(280662211837031421377505349403711176578, 8)"
    },
    "z3": {
      "CLASS": "IntermediateReal",
      "value": 3.0,
      "label": null,
      "uid": "(280662211837031421377505349403711176578, 5, 0)",
      "u_components": {
        "CLASS": "Vector",
        "index": [],
        "value": []
      },
      "d_components": {
        "CLASS": "Vector",
        "index": [
          "(280662211837031421377505349403711176578, 7)",
          "(280662211837031421377505349403711176578, 8)"
        ],
        "value": [
          1.0,
          1.0
        ]
      },
      "i_components": {
        "CLASS": "Vector",
        "index": [
          "(280662211837031421377505349403711176578, 5, 0)"
        ],
        "value": [
          1.7320508075688772
        ]
      }
    }
  },
  "tagged_complex": {
    "x4": {
      "CLASS": "Complex",
      "n_re": "x4_re",
      "n_im": "x4_im",
      "label": null
    },
    "y4": {
      "CLASS": "Complex",
      "n_re": "y4_re",
      "n_im": "y4_im",
      "label": null
    },
    "z4": {
      "CLASS": "Complex",
      "n_re": "z4_re",
      "n_im": "z4_im",
